### ISSUE TITLE
Responses contain duplicate access-control-allow-origin: * HTTP headers

### ISSUE THREAD

**Issue by NicolasFlamel1** [Grinnode-live/grinnode.live#26]
Responses from https://grinnode.live/v2/foreign contain duplicate `access-control-allow-origin: *` HTTP headers.

This can be tested with the following curl commands where the responses will look similar to this:
```
HTTP/1.1 200 OK
date: Mon, 03 Jan 2022 05:43:32 GMT
server: Apache/2.4.38 (Debian)
access-control-allow-origin: *
access-control-allow-methods: POST, GET
access-control-allow-origin: *
access-control-allow-headers: Content-Type, Authorization
content-type: application/json
content-length: 2
set-cookie: REALHOST=.1;
vary: Accept-Encoding,Origin
vary: Accept-Encoding,Origin
```

Preflight test:
```
curl -H "Access-Control-Request-Method: POST" -X OPTIONS -v https://grinnode.live/v2/foreign
```
POST test:
```
curl -d '{"id":"json","method":"get_tip","params":{}}' -v https://grinnode.live/v2/foreign
```
The duplicate `access-control-allow-origin: *` headers conflict with Chrome's CORS checks as demonstrated in the screenshot below.

![Chrome Error](https://user-images.githubusercontent.com/85004915/147911639-084bc3fa-7660-44c9-b8a3-654ac2a30e24.png)

Web wallets can't directly use grinnode.live due to this issue.

**Comment by stakervali** [comment]
We are looking into this, thanks for pointing out the issue @NicolasFlamel1.

**Comment by MCM-Mike** [comment]
>Responses from https://grinnode.live/v2/foreign contain duplicate access-control-allow-origin: * HTTP headers.

Currently we only support API request including the corresponding ports `3413`.
In your example you are querying the API without adding the officially supported ports.

**Your query:**
```curl -d '{"id":"json","method":"get_tip","params":{}}' -v https://grinnode.live/v2/foreign```

```
> POST /v2/foreign HTTP/1.1
> Host: grinnode.live
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Length: 44
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 44 out of 44 bytes
< HTTP/1.1 200 OK
< date: Mon, 28 Feb 2022 10:53:28 GMT
< server: Apache/2.4.38 (Debian)
< access-control-allow-origin: *
< access-control-allow-methods: POST, GET
< access-control-allow-origin: *
< access-control-allow-headers: Content-Type, Authorization
< content-type: application/json
< content-length: 314
< set-cookie: REALHOST=.1;
< vary: Accept-Encoding,Origin
< vary: Accept-Encoding,Origin
< 
{
  "id": "json",
  "result": {
    "Ok": {
      "height": 1634919,
      "last_block_pushed": "0002aff3d8e56c6ec2c0bfcfdf4bcd7ae09d8572b0fcfaf39703a45b79e44531",
      "prev_block_to_last": "0002a2f9741d320813138cf05c0f552348a6d0e759f14c0c60834479a4f2220d",
      "total_difficulty": 1897915350349540
    }
  }

```

here we clearly see the `< access-control-allow-origin: *` duplicate header's.

**Solution:**

**Query with GRIN ports**
```curl -d '{"id":"json","method":"get_tip","params":{}}' -v https://grinnode.live:3413/v2/foreign```

```
> POST /v2/foreign HTTP/1.1
> Host: grinnode.live:3413
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Length: 44
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 44 out of 44 bytes
< HTTP/1.1 200 OK
< access-control-allow-origin: *
< access-control-allow-headers: Content-Type, Authorization
< content-type: application/json
< content-length: 314
< date: Mon, 28 Feb 2022 10:55:08 GMT
< vary: Accept-Encoding,Origin
< vary: Accept-Encoding,Origin
< 
{
  "id": "json",
  "result": {
    "Ok": {
      "height": 1634920,
      "last_block_pushed": "00028f061a99821fa3b01432d3e104c6a6e0bbaba432127b779c709d11b6582e",
      "prev_block_to_last": "0002aff3d8e56c6ec2c0bfcfdf4bcd7ae09d8572b0fcfaf39703a45b79e44531",
      "total_difficulty": 1897915693085265
    }
  }
``` 

We allowed querying without ports for some special applications like the Ironbelly wallet, but it was never intented to be used without the corresponding ports, due to our [GRIN node setup](https://github.com/Grinnode-live/grinnode.live#infrastructure-grinnodelive)

@stakervali 
I think I might confused the public here because I had some public references where I did not specified a port:

- https://github.com/Grinnode-live/grinnode.live/blob/master/linux-grin-commands-collection.md
Could you please go through the repository/organisation and find references to an API call without a port added and compile a 

list please?

**Comment by NicolasFlamel1** [comment]
@MCM-Mike Thanks! I can confirm that it works when including the port.
