### ISSUE TITLE
Missing Payout request on Grinmint

### ISSUE THREAD

**Issue by Grinminer** [Grinnode-live/grinnode.live#40]
Hi there,

I've requested a payout yesterday evening but I still didn't receive the slatepack message.

My email is grinminerpino@gmail.com.

Can you please verify what's wrong?

**Comment by marekyggdrasil** [comment]
Dear @Grinminer, sorry for your inconvenience. Yes we received some withdrawal problems report, I investigated and found out that due to node issues our payout daemon was down. After I restarted it the payouts were processed. I investigated yours and it appears to have passed as well. If not, please re-open this issue and let me know.
